### ISSUE TITLE
vim (-python +python3): command "python << EOF" not availablesc

### ISSUE THREAD

**Issue by Felicis** [coot/atp_vim#38]
Hi, 
when I open a tex file it complains about python being not available, even though I have "python3". 

I believe the alert comes from the python call with `python` (l.68), as when I change it to `python3` it works for me. 
Do you know any way to make the actual python call be "python" or "python3" alternatively?

best, felicis
![selection_002](https://cloud.githubusercontent.com/assets/11877488/22661266/0f047106-eca5-11e6-9650-c336637d74cf.png)

**Comment by Felicis** [comment]
The problem also occurs in a couple of other files.... the same though ^^

**Comment by coot** [comment]
yes, we can support python3 with
```
exe (has("python3") ? "python3" : "python") . " << EOF"
```

Are you interested in making a pull request? There is some work to be done to make all the python code 2 and 3 compatible.

**Comment by Felicis** [comment]
sure ^^
I just tried your snippet and it works for me. 
For vim startup it's only those two occurences... though I should check out other occurences of this idiom in all the code.

**Comment by Felicis** [comment]
oh.... yeah, the idiom's been used a couple of times...
I don't know, should I change them all? (> 15 occurences)

**Comment by Felicis** [comment]
Is there a way of testing everything is ok?
I feel somewhat uneasy submitting a pull request without testing.... :thinking:

**Comment by coot** [comment]
Not really, there is no other way as use it for some time.  And I am not writing any latex now 🤔

**Comment by Felicis** [comment]
We'll see ^^

**Comment by coot** [comment]
I fixed some errors, and switched to `:pyx` command.  Can you test it too?

**Comment by Felicis** [comment]
sure, only I would need some help on how to test the version (I just tried updating ATP and noticed even this very issue is actually not fixed with me - I used latex very little lately).

I updated to version 12.5 through `:UpdateATP`, though `:h atp-news` still tells me I'm at 12.1 :(

**Comment by coot** [comment]
I haven't pushed anything to vim.org, so you will need to clone this repo.

**Comment by Felicis** [comment]
ah, ok, will try ^^

**Comment by coot** [comment]
I have to remove that command...

**Comment by Felicis** [comment]
^^

**Comment by Felicis** [comment]
Ok, I have tried getting it to work, but I weren't successfull :(
Do you know any technique of testing the plugin by adding it manually to vim?
Best ^^

**Comment by coot** [comment]
Just clone the repo in some directory, let say `~/atp_plugin` and add `~/atp_plugin` to `runtimepath`.  I use [Vim Addon Manager](https://github.com/MarcWeber/vim-addon-manager) and it's doing basically that. There are a few other plugin managers which can clone a git repo for you and manage the `runtimepath` vim setting.

**Comment by Felicis** [comment]
I tried dumping it in ~/.vim and adding "" to my .vimrc and it deosn't complain about anything, but I cannot open the manpage of the plugin.... How can I determine if the plugin is successfully loaded?
I tried issuing a command (":Latexmk") but it didn't find it :(

**Comment by janblue** [comment]
I have exactly the same problem. I'm using vim (-python +python3) and automatic tex plugin, getting two python << EOF errors when opening a tex-File. When changing the line to python3 << EOF, the errors (only at the start) are gone, but nevertheless it seems impossible  to use the python-scripts, so f.e. I can't jump to errors using the quickfix window. Exists a solution or working around? Vim and the atp-plugin are such great tools, but without working correctly inefficient to use due to the compile-cyclus.

Thanks for any help or hints,
